#
# Copyright (c) 2012-2015 Krzysztof Jusiak (krzysztof at jusiak dot net)
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
os:
  - Visual Studio 2015

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

branches:
  except:
    - gh-pages

environment:
  fast_finish: true
  global:
    DRMEMORY: --memcheck="drmemory -batch -exit_code_if_errors 1"

  matrix:
  - CFG: cmake
  - CFG: bjam

matrix:
  fast_finish: true

install:
  - cinst drmemory
  - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat
  - git submodule update --init --recursive
  - IF %CFG%==bjam_test_analyze cd build && bootstrap.bat --with-toolset=msvc-14.0
  - IF %CFG%==bjam_test_memcheck cd build && bootstrap.bat --with-toolset=msvc-14.0
  - IF %CFG%==bjam_example cd build && bootstrap.bat --with-toolset=msvc-14.0
  - set PATH=C:\Program Files (x86)\Dr. Memory\bin;%PATH%

build_script:
  - IF %CFG%==bjam pushd . && cd test && ..\build\b2 -sBOOST_ROOT=..\build -j2 -q --toolset=msvc-14.0 analyze && popd
  - IF %CFG%==bjam pushd . && cd example && ..\build\b2 -sBOOST_ROOT=..\build -j2 -q --toolset=msvc-14.0&& popd
  - IF %CFG%==cmake pushd . && cd build && cmake .. && cmake --build . && ctest --output-on-failure

