language: cpp

compiler:
  - clang

before_install:
  - rm -rf boost_1_55_0
  - wget -c http://downloads.sourceforge.net/project/boost/boost/1.55.0/boost_1_55_0.tar.gz
  - tar zxf boost_1_55_0.tar.gz
  - ln -s . boost_1_55_0/libs/di
  - cd boost_1_55_0/libs/di/test

script:
  - bjam -j2

notifications:
  recipients:
    - krzysztof@jusiak.net
  email:
    on_success: change
    on_failure: always

