language: cpp

os:
  - linux
  - osx

compiler:
  - clang

before_install:
  - git submodule init && git submodule update
  - cd build && ./bootstrap.sh --with-toolset=clang

script:
  - ./bjam ../example ../test

after_success:

branches:
  only:
    - cpp14

notifications:
  recipients:
    - krzysztof@jusiak.net
  email:
    on_success: change
    on_failure: always

