language: c++

matrix:
    include:
        - env: TOOLSET=clang-3.4
          addons: &clang34
              apt:
                  packages:
                      - clang-3.4
                      - libstdc++-4.9-dev
                      - valgrind
              sources:
                  - ubuntu-toolchain-r-test
                  - llvm-toolchain-precise-3.4

        - env: TOOLSET=clang-3.5
          addons: &clang35
              apt:
                  packages:
                      - clang-3.5
                      - libstdc++-4.9-dev
                      - valgrind
              sources:
                  - ubuntu-toolchain-r-test
                  - llvm-toolchain-precise-3.5

        - env: TOOLSET=clang-3.6
          addons: &clang36
              apt:
                  packages:
                      - clang-3.6
                      - libstdc++-4.9-dev
                      - valgrind
              sources:
                  - ubuntu-toolchain-r-test
                  - llvm-toolchain-precise-3.6

        - env: TOOLSET=clang-3.7
          addons: &clang37
              apt:
                  packages:
                      - clang-3.7
                      - libstdc++-4.9-dev
                      - valgrind
              sources:
                  - ubuntu-toolchain-r-test
                  - llvm-toolchain-precise

        - env: TOOLSET=gcc-5.1
          addons: &gcc5
              apt:
                  packages:
                      - gcc-5
                      - valgrind
              sources:
                  - ubuntu-toolchain-r-test

env:
    global:
        - secure: "A27gNApbElRr3fqZXifVPKkB+xbxMYDFINGk2RDqul1X1Zg51M7e+ohHO9BwhEYiOGmCnFfbsVUP11XyFIH6kzWmxw9mhy8YDglbYfeyu6grxtU3mHElz8W7wO5OCPFPWXQf23sVYE8AWyjj6M+t3oyLJhPXCcYI7uMHEQm10CQ="

    matrix:
        - TOOLSET=clang # osx

os:
    - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then sudo pip install cpp-coveralls; fi
  - cd build
  - ./bootstrap.sh --with-toolset=${TOOLSET};

script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./b2 -j4 -q --toolset=${TOOLSET} debug-symbols=off cxxflags="-stdlib=libc++" linkflags="-stdlib=libc++" ../test ../example; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ] && [ "$CXX" == "g++" ]; then ./b2 -j4 -q --toolset=${TOOLSET} debug-symbols=off ../test ../example; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ] && [ "$CXX" == "clang++" ]; then ./b2 -j4 -q --toolset=${TOOLSET} debug-symbols=off cxxflags="-stdlib=libc++" linkflags="-stdlib=libc++" ../test ../example; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then find .. -type f -executable | grep "\.test" | xargs -i% valgrind --error-exitcode=-1 %; fi

after_success:
  #- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CXX" == "g++" ]; then coveralls -r . -b test/ --repo-token c3V44Hj0ZTKzz4kaa3gIlVjInFiyNRZ4f; fi

branches:
  only:
    - cpp14

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/743f46341bea58bbe3ca
        on_success: change
        on_failure: always
        on_start: false

