language: cpp

compiler:
  - clang

before_install:
  - sudo apt-get --yes install libboost1.53-dev

script:
  - ls
  - cd di/test && bjam -j2

notifications:
  recipients:
    - krzysztof@jusiak.net
  email:
    on_success: change
    on_failure: always

