language: cpp

os:
  - linux
  - osx

compiler:
  - clang
#  - gcc

before_install:
  - sudo pip install cpp-coveralls
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq install valgrind; fi
  - cd build && ./bootstrap.sh --with-toolset=clang

script:
  - ./b2 -j4 -q --toolset=clang debug-symbols=off cxxflags="-stdlib=libc++" linkflags="-stdlib=libc++" ../test ../example
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then find .. -type f -executable | xargs -i% valgrind --error-exitcode=-1 %; fi

after_success:
  #- coveralls --exclude benchmark --exclude test --gcov-options '\-lp' --gcov 'gcov-4.8'

branches:
  only:
    - cpp14

