language: cpp

compiler:
  - gcc
  - clang

before_install:
  - rm -rf boost
  - wget https://gist.githubusercontent.com/krzysztof-jusiak/11c105090bf6a9963dc9/raw/9a8b4565dcf6a250d410fe4e860f541ee7821221/get_boost.sh
  - chmod +x get_boost.sh
  - ./get_boost.sh align bind config core function mpl predef preprocessor typeof smart_ptr test type_traits utility
  - mkdir boost/libs/di
  - cp -r doc example include test boost/libs/di
  - git clone https://github.com/krzysztof-jusiak/gcov-coveralls.git
  - sudo cp gcov-coveralls/gcov-coveralls.sh /usr/bin
  - cd boost
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - sudo apt-get update -qq
  - sudo apt-get -qq install valgrind
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-4.7; fi
  - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.7 90; fi
  - if [ "$CXX" == "g++" ]; then ./bootstrap.sh --with-toolset=gcc; fi
  - if [ "$CXX" == "clang++" ]; then ./bootstrap.sh --with-toolset=clang; fi
  - ./b2 headers

script:
  - pushd .
  - cd libs/di/example && ../../../b2 -j2
  - popd
  - pushd .
  - if [ "$CXX" == "g++" ]; then cd libs/di/test && ../../../b2 -j2 coverage ; fi
  - if [ "$CXX" == "clang++" ]; then cd libs/di/test && ../../../b2 -j2 ; fi
  - popd
  #- find bin.v2/libs/di -type f -executable | xargs -i% valgrind --error-exitcode=-1 --leak-check=full --track-origins=yes --show-reachable=yes % >/dev/null

after_success:
  - if [ "$CXX" == "g++" ]; then gcov-coveralls.sh "/usr/bin/gcov-4.7" "libs/di/test" "bin.v2/libs/di/test" "boost/di/" "L0bLvIumNdzR0XiKdKJSHgKopNnnO9mul" ; fi

branches:
  only:
    - master

notifications:
  recipients:
    - krzysztof@jusiak.net
  email:
    on_success: change
    on_failure: always

