language: cpp

os:
  - linux
  - osx

compiler:
  - clang
#  - gcc

before_install:
  - sudo pip install cpp-coveralls
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq install valgrind; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq libstdc++-4.9-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo wget http://ftp.us.debian.org/debian/pool/main/g/gcc-5/gcc-5_5-20150404-1_amd64.deb; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo dpkg -i gcc-5_5-20150404-1_amd64.deb; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then g++ -v; fi
  - cd build && ./bootstrap.sh --with-toolset=clang

script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./b2 -j4 -q --toolset=clang debug-symbols=off cxxflags="-stdlib=libc++" linkflags="-stdlib=libc++" ../test ../example; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./b2 -j4 -q --toolset=clang debug-symbols=off ../test ../example; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then find .. -type f -executable | grep "\.test" | xargs -i% valgrind --error-exitcode=-1 %; fi

after_success:
  #- coveralls --exclude benchmark --exclude test --gcov-options '\-lp' --gcov 'gcov-4.8'

branches:
  only:
    - cpp14

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/743f46341bea58bbe3ca
        on_success: change
        on_failure: always
        on_start: false

