language: c++
compiler: clang
os: linux
sudo: false


matrix:
  allow_failures:
    - env: BOOST_VERSION=trunk

  include:
    # clang 3.5
    - env: CLANG_VERSION=3.5 BOOST_VERSION=1.57.0 UNIT_TESTS=true
      addons: &clang35
        apt:
          packages:
            - clang-3.5
            - valgrind
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5

    - env: CLANG_VERSION=3.5 BOOST_VERSION=1.58.0 UNIT_TESTS=true
      addons: *clang35

    - env: CLANG_VERSION=3.5 BOOST_VERSION=trunk UNIT_TESTS=true
      addons: *clang35

    # clang 3.6
    - env: CLANG_VERSION=3.6 BOOST_VERSION=1.57.0 UNIT_TESTS=true
      addons: &clang36
        apt:
          packages:
            - clang-3.6
            - valgrind
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6

    - env: CLANG_VERSION=3.6 BOOST_VERSION=1.58.0 UNIT_TESTS=true
      addons: *clang36

    - env: CLANG_VERSION=3.6 BOOST_VERSION=trunk UNIT_TESTS=true
      addons: *clang36

    # clang 3.7
    - env: CLANG_VERSION=3.7 BOOST_VERSION=1.57.0 UNIT_TESTS=true
      addons: &clang37
        apt:
          packages:
            - clang-3.7
            - valgrind
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise # latest

    - env: CLANG_VERSION=3.7 BOOST_VERSION=1.58.0 UNIT_TESTS=true
      addons: *clang37

    - env: CLANG_VERSION=3.7 BOOST_VERSION=trunk UNIT_TESTS=true
      addons: *clang37

    # Release benchmarks
    - env: CLANG_VERSION=3.5 BOOST_VERSION=1.57.0 BENCHMARKS=true BUILD_TYPE=Release
      addons: *clang35

    - env: CLANG_VERSION=3.6 BOOST_VERSION=1.57.0 BENCHMARKS=true BUILD_TYPE=Release
      addons: *clang36

    - env: CLANG_VERSION=3.7 BOOST_VERSION=1.57.0 BENCHMARKS=true BUILD_TYPE=Release
      addons: *clang37

    # Debug benchmarks
    #
    # Note: We do _not_ run the Debug benchmarks on Clang 3.5, because it does not
    # have support for debug information for `auto`, and it produces compilation
    # errors. So we use the default build type instead for Clang 3.5.
    - env: CLANG_VERSION=3.5 BOOST_VERSION=1.57.0 BENCHMARKS=true
      addons: *clang35

    - env: CLANG_VERSION=3.6 BOOST_VERSION=1.57.0 BENCHMARKS=true BUILD_TYPE=Debug
      addons: *clang36

    - env: CLANG_VERSION=3.7 BOOST_VERSION=1.57.0 BENCHMARKS=true BUILD_TYPE=Debug
      addons: *clang37


env:
    global:
        - secure: "A27gNApbElRr3fqZXifVPKkB+xbxMYDFINGk2RDqul1X1Zg51M7e+ohHO9BwhEYiOGmCnFfbsVUP11XyFIH6kzWmxw9mhy8YDglbYfeyu6grxtU3mHElz8W7wO5OCPFPWXQf23sVYE8AWyjj6M+t3oyLJhPXCcYI7uMHEQm10CQ="

    matrix:
        - TOOLSET=clang

install:
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then sudo pip install cpp-coveralls; fi
  - travis_wait travis_retry svn --quiet co http://llvm.org/svn/llvm-project/libcxx/trunk libcxx
  - (mkdir libcxx/build && cd libcxx/build && CXX=clang cmake .. -DLIBCXX_CXX_ABI=libstdc++ -DLIBCXX_CXX_ABI_INCLUDE_PATHS="/usr/include/c++/4.6;/usr/include/c++/4.6/x86_64-linux-gnu")
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then make -C libcxx/build cxx -j2; fi

before_script:
  - export LIBCXX=$PWD/libcxx/build/include/c++/v1
  - export LIBCXX_DIR=$PWD/libcxx/build/lib
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$LIBCXX_DIR
  - (cd build && ./bootstrap.sh --with-toolset=${TOOLSET})

script:
  - (cd test && ../build/b2 -sBOOST_ROOT=../build -j2 -q --toolset=${TOOLSET} debug-symbols=off cxxflags="-stdlib=libc++ -I$LIBCXX" linkflags="-stdlib=libc++ -L$LIBCXX_DIR" ${COVERAGE})
  - (cd example && ../build/b2 -sBOOST_ROOT=../build -j2 -q --toolset=${TOOLSET} debug-symbols=off cxxflags="-stdlib=libc++ -I$LIBCXX" linkflags="-stdlib=libc++ -L$LIBCXX_DIR")
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then find .. -type f -executable | grep "\.test" | xargs -i% valgrind --error-exitcode=-1 %; fi

after_success:
  - if [ "${COVERAGE}" != "" ]; then coveralls -r . -b test/ --repo-token c3V44Hj0ZTKzz4kaa3gIlVjInFiyNRZ4f; fi
  - if [ "${DOCUMENTATION}" != "" ]; then cd doc && ../build/b2 -sBOOST_ROOT=../build; fi

branches:
  only:
    - travis

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/743f46341bea58bbe3ca
        on_success: change
        on_failure: always
        on_start: false

