language: c++

matrix:
    include:
        - env: COMPILER=clang-3.4
          addons: &clang34
              apt:
                  packages:
                      - clang-3.4
                      - valgrind
              sources:
                  - ubuntu-toolchain-r-test
                  - llvm-toolchain-precise-3.4

        - env: COMPILER=clang-3.5
          addons: &clang35
              apt:
                  packages:
                      - clang-3.5
                      - valgrind
              sources:
                  - ubuntu-toolchain-r-test
                  - llvm-toolchain-precise-3.5

        - env: COMPILER=clang-3.6
          addons: &clang36
              apt:
                  packages:
                      - clang-3.6
                      - valgrind
              sources:
                  - ubuntu-toolchain-r-test
                  - llvm-toolchain-precise-3.6

        - env: COMPILER=clang-3.7
          addons: &clang37
              apt:
                  packages:
                      - clang-3.7
                      - valgrind
              sources:
                  - ubuntu-toolchain-r-test
                  - llvm-toolchain-precise

        - env: COMPILER=gcc-5
          addons: &gcc5
              apt:
                  packages:
                      - gcc-5
                      - valgrind
              sources:
                  - ubuntu-toolchain-r-test

env:
    global:
        - secure: "A27gNApbElRr3fqZXifVPKkB+xbxMYDFINGk2RDqul1X1Zg51M7e+ohHO9BwhEYiOGmCnFfbsVUP11XyFIH6kzWmxw9mhy8YDglbYfeyu6grxtU3mHElz8W7wO5OCPFPWXQf23sVYE8AWyjj6M+t3oyLJhPXCcYI7uMHEQm10CQ="

    matrix:
        - COMPILER=clang # osx

os:
    - osx

install:
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then sudo pip install cpp-coveralls; fi
  - echo | g++ -Wp,-v -x c++ - -fsyntax-only
  - travis_wait travis_retry svn --quiet co http://llvm.org/svn/llvm-project/libcxx/trunk libcxx
  - mkdir libcxx/build
  - (cd libcxx/build && cmake .. -DLIBCXX_CXX_ABI=libstdc++ -DLIBCXX_CXX_ABI_INCLUDE_PATHS="/usr/include/c++/4.6;/usr/include/c++/4.6/x86_64-linux-gnu")
  - make -C libcxx/build cxx -j2

before_script:
  - cd build
  - ./bootstrap.sh

script:
  - ./b2 -j4 -q --toolset=${COMPILER} debug-symbols=off cxxflags="-stdlib=libc++" linkflags="-stdlib=libc++" ../test ../example
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then find .. -type f -executable | grep "\.test" | xargs -i% valgrind --error-exitcode=-1 %; fi

after_success:
  #- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CXX" == "g++" ]; then coveralls -r . -b test/ --repo-token c3V44Hj0ZTKzz4kaa3gIlVjInFiyNRZ4f; fi

branches:
  only:
    - cpp14

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/743f46341bea58bbe3ca
        on_success: change
        on_failure: always
        on_start: false

