language: cpp

os:
#  - linux
  - osx

compiler:
  - clang
#  - gcc

before_install:
  - cd build && ./bootstrap.sh --with-toolset=clang

script:
  - ./b2 -j4 -q --toolset=clang cxxflags="-stdlib=libc++" linkflags="-stdlib=libc++" ../test ../example

after_success:

branches:
  only:
    - cpp14

notifications:
  recipients:
    - krzysztof@jusiak.net
  email:
    on_success: change
    on_failure: always

