language: c++

os: linux
#  - osx

sudo: required

matrix:
  include:
    - env: TOOLSET=clang-3.4
      addons: &clang34
        apt:
          packages:
            - clang-3.4
            - libstdc++-5-dev
            - valgrind
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.4

    - env: TOOLSET=clang-3.5
      addons: &clang35
        apt:
          packages:
            - clang-3.5
            - libstdc++-5-dev
            - valgrind
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5

    - env: TOOLSET=clang-3.6
      addons: &clang36
        apt:
          packages:
            - clang-3.6
            - libstdc++-5-dev
            - valgrind
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6

    - env: TOOLSET=clang-3.7
      addons: &clang37
        apt:
          packages:
            - clang-3.7
            - libstdc++-5-dev
            - valgrind
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise

    - env: TOOLSET=gcc-5 VARIANT=coverage DOCUMENTATION=publish
      addons: &gcc5
        apt:
          packages:
            - g++-5
            - libstdc++-5-dev
            - valgrind
          sources:
            - ubuntu-toolchain-r-test

env:
  global:
    - secure: "A27gNApbElRr3fqZXifVPKkB+xbxMYDFINGk2RDqul1X1Zg51M7e+ohHO9BwhEYiOGmCnFfbsVUP11XyFIH6kzWmxw9mhy8YDglbYfeyu6grxtU3mHElz8W7wO5OCPFPWXQf23sVYE8AWyjj6M+t3oyLJhPXCcYI7uMHEQm10CQ="

  matrix:
    - TOOLSET=clang # for osx

before_script:
  - (cd build && ./bootstrap.sh)

script:
  - (cd test && ../build/b2 -sBOOST_ROOT=../build -j2 -q --toolset=${TOOLSET} debug-symbols=off ${COVERAGE})
  - (cd example && ../build/b2 -sBOOST_ROOT=../build -j2 -q --toolset=${TOOLSET} debug-symbols=off)
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then find .. -type f -executable | grep "\.test" | xargs -i% valgrind --error-exitcode=-1 %; fi

after_success:
  - if [ "${COVERAGE}" != "" ]; then sudo pip install cpp-coveralls; coveralls -r . -b test/ --repo-token c3V44Hj0ZTKzz4kaa3gIlVjInFiyNRZ4f; fi
  - if [ "${DOCUMENTATION}" != "" ]; then cd doc && ../build/b2 -sBOOST_ROOT=../build; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/743f46341bea58bbe3ca
  on_success: change
  on_failure: always
  on_start: false

