platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

branches:
  only:
    - msvc2015

install:
  - git submodule update --init --recursive
  - cd build && bootstrap.bat --with-toolset=msvc-14.0

build:
  - cd build && b2 -j2 -q --toolset=msvc-14.0 ../test ../example

test:

test_script: OFF
deploy: OFF

