platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

branches:
  only:
    - msvc2015

install:
  - cd build && bootstrap --with-toolset=msvc-14.0
  - cd build && b2 -j2 -q --toolset=msvc-14.0 ../test ../example

build: OFF
test: OFF
test_script: OFF
deploy: OFF

