platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

os: Visual Studio 2015 CTP 6

branches:
  only:
    - cpp14

install:
  - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat
  - git submodule update --init --recursive
  - cd build && bootstrap.bat --with-toolset=msvc-14.0

build_script:
  - cd test && ..\build\b2 -sBOOST_ROOT=..\build -j2 -q --toolset=msvc-14.0 msvc2015

